# Homologacao (mantido como hoje)
app.base-url=http://reserva360hml.grupoccaa.com.br:8081
app.frontend-url=http://reserva360hml.grupoccaa.com.br:8081
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:8081,http://reserva360hml.grupoccaa.com.br:8081
