trigger:
- main

stages:
- stage: TesteServidor
  displayName: 'Teste de Servidor'
  jobs: 
  - deployment: DeployDevelopment
    displayName: "Teste de deploy"
    environment: 
     name: Development
     resourceType: VirtualMachine
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName:  'Criacao de arquivo no servidor'
            inputs:
              script: echo "Hello World!" > /home/vboxuser/teste.txt